// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rjsihrlncbekoobwsvxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJqc2locmxuY2Jla29vYndzdnh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY2NTM4MzQsImV4cCI6MjA2MjIyOTgzNH0.887jN3ks-3PDfE5wKX4a8dTuMDIj6fmjUPPn2r0ksM0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);